language: node_js
node_js:
- 6.9.4
deploy:
  provider: heroku
  api_key:
    secure: gl8Af9hM+dx546/rntaqW9rZdhgGB/JjVYnkVSs1uhyr0lNKqBETteuH6ahH27QLpkym9pn3ozsjZk09v+wVaLljQyKB2vQt10dWAgzrTtr533iLDkTifFlZ2CKEyrNpu+tRu43iN+vqwUb5xmfR5/1gBeRgtIEay57dgxAxTevD5gOHAh3sZf/AAKGMZ1RsR+zuay5ZnEs5Y1ShJCPJKH6BgE4+ZouUYve/WoPfgBlRbpsEhWSilZXlRHz84x3Dil6Ppw+M3s4+mFXUYXcXpkVkbLK8Fw8ryhIaMuRmUL48Ua5ltvQV8BoLh0DeNidTpKQpeWfY/JJVqSkI9n4RZb5rv7sMh/aNiU1DQMUBxb8zW7R8c39s2tz+gHtY2mJ82LcBoFRxCotsIMVmNCjVHP5nb9NCL+QfIPONSCJ4hLqFRgK9PikDCWKGZ67rAfW6cATJThxfnohVZygxyJlhrNoYXC9nL3l0TavAZrI0KC5eDQIWTEClrqqJW+QG8jwoxMdnA3vV00RfeMwQmJf8c5qj0ZmH1WafinKRHHA/xDfXMdatiTfxUOplqs3lT3lERllwytqSYCNuGn72YaxgGkdGZgb7CQCyz27Ji2wTZzepC23N2jagg5jQkyxwV+E5BYBpmGZA8cc7sN83vcnQAzniEwBfPkhk50fHHnVy52s=
  app: finance_project
  on:
    repo: evedal/finance_project

  # MySQL setup
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE travis;'
  - mysql -u root test < database/db.sql