language: node_js
node_js:
- 6.9.4
deploy:
  provider: heroku
  api_key:
    secure: f20iZ/t3GWNxq4Lcgju2jUfeQxe5zcyD7krQ+nc8WYpDUCEp0WHR3tnieWf9Qq3nnEfQRRyS3DNqjLuKQWI8/OeFuezVD7rHgRYI4pzVADhx4z4gT/6hghss9gE4aZjkPXIYVUMj3tTdDQGHXFhI+feZ9fTRl8n5T3sOh5nVULWoKB2g1yPAgKpmJQW4/irOB1LBNJcgVvwmLJSYiIkzmDY/KHU+IpIPUhIMctKeryvem/IlnQyqMCNuuwGXVXNhNV7q5Wi0fDmJc5ioBiqxM5QD3UL1N+RQWDvbahsFnETdigtWJOCrkP9tpzmQTQBpdU9sBGL6pGT2FL4WLEjAesyWbbPbtKiWAyzrp1wl871OgQKXWO/CdAM4lpNf+seujKREYB6pVc2FOV1kFZn2in5fn8Zdao7OY1Pm9+KHdSJEP8WZgT7IIWcFlM854G0Yp/fGYkCAhj4swKSQAtG+swzFBPxlNRKPXnh50CyHVuR7Dx96B1Davm+GQqcJ5u5OD9FVBCU9elRToKenceHWYyEbodhEPNPmPy//W+m3fncIwiQrUtnM2EflH4oRy4VNqlxNeRzwjkEDRtV5raB4KS8k7fE5JTQ59cNHlmAxLaUHbMdRwZkVwwI4PJ65kJ81mYRy5fwRLCKCn1ZUZS8XTYwV4HOGnoPS8mqEeLoGyac=
  app: finance_project
  on:
    repo: evedal/finance_project

