language: node_js
node_js:
- 6.9.4
deploy:
  provider: heroku
  api_key:
    secure: "er/huQnxRz7yMXvZEkydNjaKOTHEfVXB2XaX2s1VeHgygoSSPv0EmhI2SxrMTwTGtor8r89HqFOb1j3VMvhucDAmD9iDGhJCV9LSqg1IqW1JsZM83K9PWfj0mf2s4b2Mp8bjRu57mMg5q6fl/S7Jkp5bBD8FKHCwLzd4PFTIuhDWXhZFy/3eOObIcbV0KCf8ZntNySi9Lefr3PnVYeyT+Gpip14hVumEQNpBpCaAwi1rp+n+tR9NWgeeouboAB2FckVNPGdZerhXKQ35QbXY/AXC1YuhXazD8sSK2MYvRsCl/S3fBeBbxdHqRFjlYfmPPLuK1gDikxvmhf1Am++JW8os9LXSL9QAMKaLCmj9Ijwkv3oyjUuF6BKN7BaMU8bxT5lBJbtNDwPJ8KhrNF5KOVTNzkkpjSzX3G1cDaBwZOXM6IO0D8/61Amu+fEB+0T8rCVGuK92eDvNJNBbGQH/5+KT/UTZ0WFAOb9R/9BUdt6QpXRGGm8t94l106GhVxaF3rHUw9u1h93PaRER9aryRgWgPK+0UmFCHzQZ62LK5gLotUEywAb1La72I9PzfQg0kYbxdfuTENSMtay6bQZrJie9SKTntQ921dPwd3G7FMieaDroFT5MvD6zpkDABGe3Ix8Kyw8xPu5kLc/O1n0YHbqfmZddrTeiXMWcm84nBIc="
  app: finance_project
  on:
    repo: evedal/finance_project
